name: Build and Test

on:
  push:
    branches:
      - main  # Change this to your main branch name

jobs:
  build:
    runs-on: ubuntu-latest  # Specify that this workflow runs on Ubuntu

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Action to checkout your repository's code
    
    - name: Set up google test
      uses: Bacondish2023/setup-googletest@v1
        
    - name: Set up CMake
      uses: jwlawson/actions-setup-cmake@v2.0.2
      with:
        cmake-version: '3.25.x'

    - name: Build
      run: |
        mkdir -p build
        cd build
        cmake ..
        make
    - name: Load vcan module and set up vcan0
      run: |
        sudo apt-get install -y linux-modules-extra-$(uname -r)
        sudo modprobe vcan
        sudo ip link add dev vcan0 type vcan
        sudo ip link set up vcan0

    - name: Run tests
      run: |
        cd build
        ctest --output-on-failure
